### ISSUE TITLE
Error: unexpected error found. Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by Xplodin** [Microsoft/xbox-live-developer-tools#51]
I cant use WindowsDevCenter but XDP works fine.

**Comment by bradenellis** [comment]
There was a hostname change that was causing this. This has been fixed. Pull latest source to fix.

**Comment by jicailiu** [comment]
The binaries are updated as well, you can find the zip in the releases page.
