### ISSUE TITLE
XblDevAccount.exe signin 403 Forbidden

### ISSUE THREAD

**Issue by shichen85** [microsoft/xbox-live-developer-tools#69]
Hello,

I want to use `XblPlayerDataReset.exe` to reset achievements in a sandbox. I first used `XblPCSandbox.exe` to switch to my sandbox, and then I ran `XblDevAccount.exe signin -u %MY_ACCOUNT%` to log in, which gave me the following error:

```
Error: signin failed
Response status code does not indicate success: 403 (Forbidden).
```

Would love to know how to resolve this issue. Thanks!

**Comment by rakhad** [comment]
Are you still experiencing this issue? You might not have the correct permissions. Can you check that you have the Xbox Live Tools Access permission? https://docs.microsoft.com/en-us/windows/uwp/publish/set-custom-permissions-for-account-users#product-level-permissions

**Comment by shichen85** [comment]
Thanks. Will give that a try and report back if it does not solve the problem.

**Comment by sirfaty** [comment]
We are also having this same issue trying to use the @xboxtest.com accounts from our partner center tenant.  We can use XblDevAccount to signin with our main accounts we use to access partner center, but not with the testing accounts.  Is there a special tenant or options that would allow signing in with an @xboxtest.com account?
Thanks in advance!
